### ISSUE TITLE
Decide on deployment solution for full documentation

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#23]
# Requirements
- use the virtool.com domain
- must be free

# Options to look into
1. Netlify (used for www.virtool.ca)
2. GitHub pages
3. readthedocs (free with custom domain for open source?)

**Comment by BlakeASmith** [comment]
@igboyes I think we should go with GitHub pages.

Let me know and I'll go ahead and set it up.

**Comment by igboyes** [comment]
Sounds good.
