### ISSUE TITLE
Support Job Cancellation from Front End.

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#31]
Currently, the workflow runtime does not provide a mechanism for cancelling a workflow's execution once it has started. Additionally there is currently no way for the runtime to notify the front-end application when an exception has been raised.  A method of sending messages between the front-end application and the workflow runtime will be needed to support this. 

There are a few options for this:

1. Use the MongoDB document to pass the information. Start a thread within the runtime to monitor the database document for changes. This could be done simply via polling, or perhaps with [change streams](https://docs.mongodb.com/manual/changeStreams/). 

2. Use Redis pub/sub in a similarly to how it is already used to assign jobs. A separate list of job id's could be maintained for cancellations and monitored by the runtime. 

3. Establish a direct web-socket connection between the client application and the workflow runtime. 

4. Provide an HTTP API in the runtime which the client application can make requests to. The URL endpoint for this API could be sent to the client application via it's own REST API. 

I favour option (2) as it is simple to implement and avoids the complexity involved with maintaining a direct connection between the front-end app and all workflow/job runners. 

Open to any other ideas.

**Comment by igboyes** [comment]
[Option 2 is already supported on cloud branch of virtool/virtool](https://github.com/virtool/virtool/blob/58fefd8e1304b7c37e32583a7839574978376620/virtool/jobs/job.py#L215-L228).

To clarify language, cancellation is implemented via Redis pub/sub. Job queue is via Redis lists.

**Comment by BlakeASmith** [comment]
> [Option 2 is already supported on cloud branch of virtool/virtool](https://github.com/virtool/virtool/blob/58fefd8e1304b7c37e32583a7839574978376620/virtool/jobs/job.py#L215-L228).
> 
> To clarify language, cancellation is implemented via Redis pub/sub. Job queue is via Redis lists.

Happy to go with that then.
