### ISSUE TITLE
Dynamically Provide Parameters for Workflows from UI

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#33]
## The Problem
Virtool Workflows may require arguments to be provided through the web UI. The specific arguments required vary greatly between different workflows. Thus, there is no one-size-fits-all solution to what arguments should be collected in the UI. 

Thus, we require a robust way to define what information must be collected from the user in order for a workflow to be executed as a job.  Since the arguments required by a workflow are determined by the workflow developer, they should be explicitly declared by the workflow developer. The front-end UI must then adapt to the requirements that the workflow declares. 

## Proposed Solution
In order for the UI to adapt to the workflow's requirements, a data structure must be provided to the front-end application describing which data to collect and it's type(s). This structure can be provided through the front-end's HTTP API, or by generating the definitions as part of the deployment pipeline. 

This structure would look something like this:
    
```json
{
  "workflow": "name_of_workflow",
  "arguments": {
    "argument_1": {
      "type": "string",
      "help": "an example string argument for a virtool workflow"
    },
    "argument_2": {
      "type": "file",
      "help": "an example file argument for a virtool workflow"
    },
    "optional_argument": {
      "type": "integer", 
      "help": "an example optional argument for a virtool workflow",
      "optional": true
    }
  }
}
```

Since we are already using workflow fixtures heavily, it makes sense to provide access to these arguments as fixtures. 
Based on the structure above, `argument_1`, `argument_2`, and `optional_argument` would be made available within the 
workflow code as fixtures. 

I suggest implementing an API as part of `virtool_workflow` which will;

1. Implicitly produce a JSON object describing which arguments to collect and their types. 
2. Handle retrieving arguments from the database and making them available as fixtures. 

## Possible API 

Here is an example of what the API could look like for the workflow developer. 

```python
from virtool_workflow import Workflow
from virtool_workflow.user_arguments import user_argument
from typing import IO, Optional

argument_1 = user_argument("argument_1", type=str, help="an example string argument for a virtool workflow")
argument_2 = user_argument("argument_2", type=IO, help="an example file argument for a virtool workflow")

optional_argument = user_argument("optional_argument", type=int, optional=True, 
    help="an example optional argument for a virtool workflow")

wf = Workflow()

@wf.step
def use_user_arguments(argument_1: str, argument_2: IO, optional_argument: Optional[int]):
    ...
    

```

Under the hood, the JSON structure for the front-end would be produced. 

The workflow developer could then run an "install" step via the `workflow` command line utility.

```shell script
workflow install -f my_workflow.py
```

Which would make sure that the front-end has access to the JSON structure and make the workflow 
available in the UI to be run as a job. 
 
## Another Option: Use a Configuration File

We could also define the argument and type information apart from the code in a configuration file. This could be 
a JSON file containing the exact structure used by the front-end, or something a bit nicer to deal with like YAML. 

```yaml
workflow: name
arguments:
    argument_1:
      type: str
      help: an example string argument
    argument_2:
      type: file
      help: an example file argument
    optional_argument:
      type: int
      help: an example optional argument
```

Fixtures could then be generated from the 
YAML file. 

```python
from virtool_workflow.user_arguments import load_user_arguments
from pathlib import Path

fixtures = load_user_arguments(Path("my_config.yaml"))

wf = Workflow()

@wf.step
def use_user_arguments(argument_1: str, argument_2: IO, optional_argument: Optional[int]):
    ...
    
```

This idea is not yet fully developed. Any suggestions/criticisms are welcomed.

**Comment by igboyes** [comment]
Thanks for thinking about this. I'd like to revisit it when we start adapting the COVID workflows to Virtool. For now, I am labelling **Low Priority**.

**Comment by igboyes** [comment]
Closing until we want to revisit.
