### ISSUE TITLE
Consider using pydoc-markdown In Combination With Hugo to Integrate API Documentation into the Virtool Website.

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#43]
# Background

The Virtool website uses the HUGO static site generation framework. Currently Sphinx is used to generate API documentation from the source code. Since sphinx generates HTML content and has it's own themeing engines, documentation generated with Sphinx will not be compatible with the styling of the HUGO site. 

We can host the Sphinx API documentation separatley and simply reference it on the Virtool Website. However there is value in maintaing a consistent user experience and styling between the content on the Virtool website and the virtool-workflow API docs. 

# pydoc-markdown

[pydoc-markdown](https://pypi.org/project/pydoc-markdown/) is a tool which generates python API documentation in markdown format, making it automatically compatible with HUGO.

pydoc-markdown is less powerful than Sphinx, as it does not support the comprehensive directives that sphinx does. However most features of sphinx are going unused regardless, and there is no particular feature of Sphinx that I know of which we cannot do without.

# Github Actions Integration

It would be simple enough to write a Gihub Action which could build the markdown documentation for `virtool-workflow` using `pydoc-markdown` and commit it to the `virtool/virtool-website` repository. This would allow for painless management of an API docs section on the Virtool Website. 

# Ease of Use

Sphinx relies heavily on reStructuredText, which is less well known and generally more complicated than markdown. Though it's directives are useful and powerful, there is a learning curve associated with them. pydoc-markdown enables writing markdown within docstrings in the source as opposed to reStructuredText, which keeps all the documentation markdown centered. Sphinx does support markdown through plugins, but often reStructuredText is required to do anything complicated. 

Additionaly we are already using markdown for the website content, and on Github for issues like this one. It makes sense to keep all of our documentation in markdown if we can get away with it, which I beleive we can. 

# Example

Here is an example of the rendered API documentation (Using default formatting for HUGO).

![example_docs](https://user-images.githubusercontent.com/16090356/99362983-0675e980-2869-11eb-858b-759ff5e58243.png)

**Comment by igboyes** [comment]
@BlakeASmith and @igboyes have decided to use Sphinx for docs and host docs under dedicated domain.
