### ISSUE TITLE
Limit Database Access Within Workflows, Database Authentication.

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#44]
Currently, the database can be accessed freely within workflows via the VirtoolDatabase fixture and the fixtures created for each database collection. This may become problematic in future when developers outside of the organization begin contributing workflows. 

Database access is required to setup the fixtures needed for the analysis workflows. Additionally it is required to send results of analysis workflows for the front-end to display. 

We require a solution to securely allow access to the database by the runtime while blocking access within workflows and fixtures, execept with specific exceptions.

**Comment by BlakeASmith** [comment]
# Sandboxing

The fundumental problem here is that the *runtime* process must imports a
module (*workflow.py*) which is written by a user. As such there is 
nothing preventing the `workflow.py` module from accessing values from 
the global namespace, environment variables, and other runtime specific items.

Adding authentication to the database via [SCRAM or some other mechanism](https://docs.mongodb.com/manual/core/authentication/) would make it a bit more difficult to access the database from within workflows. However there is nothing preventing a workflow developer from gaining access to the auth token which would need to be accessable within the runtime code, and as such could be discovered within the workflow code. 


Ultimatley we need to **sandbox** the workflow code in order to 
prevent it from accessing the runtime code which provides access to the
database (or credentials for accessing it).

There are several ways to do this, each providing different levels of security. Here are some of those methods. 

## Use eval() and override __import__ 

The `eval` function allows you to set the locals and globals in the context of the code being evaluated. This would limit a workflow's access to the global namespace. 

`__import__` could be overridden to prevent the workflow module from importing packages from the runtime. If they can't import the runtime modules, and don't have access to the full global scope of the runtime, it would be somewhat difficult to access the database. 


The `workflow.py` module still has access to the same filesystem as the runtime, as well as it's enviroment variables.However, it does make it more difficult to access the database and other runtime specific constructs. It won't deter a determined attacker, but anyone attempting to access the database would clearly know that they're not supposed to be doing it. 

## Full Containerization

The most secure way to sandbox the workflow module is to execute it in it's own container. Any database lookups required would be executed within the runtime process prior to running the workflow container and the required data would be provided to the container via arguments or a mounted volume. The container could produce a file containing the output results dictionary, which could then be taken in by the runtime process and sent to the database. 

The problem with this approach is that it would require `docker-in-docker` or something similar, in the context of the planned K8S deployment. 

## Run Workflows in a Separate Process Without Root Priveleges

Similarly to full containerization, Any database lookups would be performed in the runtime process and the data passed along to the workflow process. 

The MongoDB connection string, Redis connection string, and other credentials could be stored in a file which requires root privelleges to open. The runtime process will have access to the file and thus full access to the database. The workflow process will be able to import modules from `virtool_workflow_runtime` but will not be able to access the database without the proper credentials, which will be inaccessable to it since it lacks root privelleges.

**Comment by igboyes** [comment]
Closing as #83 details the chosen solution.
