### ISSUE TITLE
GitHub action problems

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#46]
# Environmental variables
Should be [set as described in documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#about-environment-variables)

# Coverage
The Codacy coverage reporter depends on the coverage output from `tox`.

1. There appears to be a name mismatch between the coverage output and the file that is uploaded.
2. The Codacy reporting does not have access to the file anyway because it is not in the same job as the coverage file.

I suggest keeping the reporting and testing in the same workflow. Only run the reporting step on the push event.

**Comment by BlakeASmith** [comment]
> I suggest keeping the reporting and testing in the same workflow. Only run the reporting step on the push event.

**Comment by BlakeASmith** [comment]
> I suggest keeping the reporting and testing in the same workflow. Only run the reporting step on the push event.


@igboyes shouldn't the coverage reporter be run on pull_request events only? Why run the codacy reporting on push?

**Comment by igboyes** [comment]
It updates the coverage data on Codacy for the branch. Coverage can't be reported to Codacy simply and securely on PR at this time.

https://github.community/t/make-secrets-available-to-builds-of-forks/16166/32

**Comment by BlakeASmith** [comment]
> It updates the coverage data on Codacy for the branch. Coverage can't be reported to Codacy simply and securely on PR at this time.
> 
> https://github.community/t/make-secrets-available-to-builds-of-forks/16166/32

**Comment by BlakeASmith** [comment]
> It updates the coverage data on Codacy for the branch. Coverage can't be reported to Codacy simply and securely on PR at this time.
> 
> https://github.community/t/make-secrets-available-to-builds-of-forks/16166/32

Okay that makes sense. Coverage will be run on the push event after the PR is merged.
