### ISSUE TITLE
Avoid multiple names for built-in fixtures

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#47]
For example: `wf`, `workflow`, `execution`, `ctx`.

Ideally, there should be one way to reference each of these fixtures. Is there any compelling reason to provide multiple names?

**Comment by BlakeASmith** [comment]
> For example: `wf`, `workflow`, `execution`, `ctx`.
> 
> Ideally, there should be one way to reference each of these fixtures. Is there any compelling reason to provide multiple names?

No reason in particular other than convenience of having a shortened name. I can see how having multiple names could get confusing though. 

Also forceing a more descriptive name is probably a good thing to do. 

I agree.

**Comment by igboyes** [comment]
The short or long choice is up to you. I am fine either way.

Will you be able to drop the logic that supports the multiple name feature by going with single names?

**Comment by BlakeASmith** [comment]
> The short or long choice is up to you. I am fine either way.
> 
> Will you be able to drop the logic that supports the multiple name feature by going with single names?

I think using the more descriptive names will be better. 

It wouldn't be difficult to remove the support for multiple names, but I don't see the harm in leaving it as an option for user defined fixtures.

**Comment by igboyes** [comment]
The downside is testing, maintaining, documenting, and supporting a feature that enables a pattern we have decided is not Pythonic or a best practice.
