### ISSUE TITLE
NotImplementedError Raised When Using uvloop (version 0.14.0) After Running `workflow run-local` 

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#55]
After running `workflow run-local`, once the workflow has finished (ie. the event loop is closed) a `NotImplementedError` is raised from  File "/usr/local/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor.

Until this is resolved the `--no-uv-loop` option can be used to avoid the issue.

**Comment by BlakeASmith** [comment]
### Full Traceback

traceback (most recent call last):
  File "/root/.local/bin/workflow", line 8, in 
      sys.exit(cli_main())
        File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/cli.py", line 109, in cli_main
	    cli()
	      File "/root/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
	          return self.main(*args, **kwargs)
		    File "/root/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
		        rv = self.invoke(ctx)
			  File "/root/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
			      return _process_result(sub_ctx.command.invoke(sub_ctx))
			        File "/root/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
				    return ctx.invoke(self.callback, **ctx.params)
				      File "/root/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
				          return callback(*args, **kwargs)
					    File "/root/.local/lib/python3.9/site-packages/virtool_workflow_runtime/cli.py", line 75, in run_local
					        asyncio.run(_run_local(f, **kwargs))
						  File "/usr/local/lib/python3.9/asyncio/runners.py", line 49, in run
						      loop.run_until_complete(loop.shutdown_default_executor())
						        File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
							  File "/usr/local/lib/python3.9/asyncio/events.py", line 253, in shutdown_default_executor
							      raise NotImplementedError
							      NotImplementedError

**Comment by BlakeASmith** [comment]
It seems that this issue is only present in python 3.9. 

After changing the `python_requires` in `setup.py` to python 3.8 and installing on that version, the issue does not persist.

**Comment by igboyes** [comment]
The latest commit on `uvloop` master branch is too fix this issue... on July 10. I think we may have to abandon. Can you do some reading to check if the performance difference is still as drastic as it was in 3.6?

**Comment by BlakeASmith** [comment]
> The latest commit on `uvloop` master branch is too fix this issue... on July 10. I think we may have to abandon. Can you do some reading to check if the performance difference is still as drastic as it was in 3.6?

:

**Comment by BlakeASmith** [comment]
> The latest commit on `uvloop` master branch is too fix this issue... on July 10. I think we may have to abandon. Can you do some reading to check if the performance difference is still as drastic as it was in 3.6?

I'll look into it

**Comment by BlakeASmith** [comment]
Looking at the latest [commmit](https://github.com/MagicStack/uvloop/commit/6ef69a797db0afe781b5ddcd74691767f8261a53) in uvloop, it does resolve the issue. But who knows when that will make it into a release.

The latest release of uvloop (0.14.0) supports python 3.8, so we could rollback to that, but the problem will persist for those running 3.9.

MagicStack's [blog post](http://magic.io/blog/uvloop-blazing-fast-python-networking/) from 2016 shows a major improvement in performance compared to asyncio. However I cannot find any more up to date comparisons of uvloop and the standard event loop. There is also not much out there about asyncio performance between 3.6 and 3.9. 

I would think that the performance improvements would be quite similar. I looked through the `What's New In Python` sections for python 3.8 and 3.9 and there is no mention of any major performance improvements.

**Comment by BlakeASmith** [comment]
Looking more closely at the [Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) changes, the problem method `.shutdown_default_executor` is called from `asyncio.run()`. However you can still use the event loop's `loop.run_until_complete()` and avoid calling `shutdown_default_executor`. 

So if we replace `asyncio.run(...)` by;

```python
loop = asyncio.get_event_loop()
loop.run_until_complete(...)
```

We can avoid the issue.

**Comment by BlakeASmith** [comment]
For reference, this is the source code for `asyncio.run`.

```
def run(main, *, debug=None):
    """Execute the coroutine and return the result.
        This function runs the passed coroutine, taking care of
	    managing the asyncio event loop and finalizing asynchronous
	        generators.
		    This function cannot be called when another asyncio event loop is
		        running in the same thread.
			    If debug is True, the event loop will be run in debug mode.
			        This function always creates a new event loop and closes it at the end.
				    It should be used as a main entry point for asyncio programs, and should
				        ideally only be called once.
					    Example:
					            async def main():
						                await asyncio.sleep(1)
								            print('hello')
									            asyncio.run(main())
										        """
											    if events._get_running_loop() is not None:
											            raise RuntimeError(
												                "asyncio.run() cannot be called from a running event loop")

														    if not coroutines.iscoroutine(main):
														            raise ValueError("a coroutine was expected, got {!r}".format(main))

															        loop = events.new_event_loop()
																    try:
																            events.set_event_loop(loop)
																	            if debug is not None:
																		                loop.set_debug(debug)
																				        return loop.run_until_complete(main)
																					    finally:
																					            try:
																						                _cancel_all_tasks(loop)
																								            loop.run_until_complete(loop.shutdown_asyncgens())
																									                loop.run_until_complete(loop.shutdown_default_executor())
																											        finally:
																												            events.set_event_loop(None)
																													                loop.close()
```

**Comment by igboyes** [comment]
Can you submit a PR that just does away with `uvloop`? I am not sure it is worth this extra code. If we have time later, we can try racing workflows to see if `uvloop` actually provides a real benefit.

**Comment by BlakeASmith** [comment]
> Can you submit a PR that just does away with `uvloop`? I am not sure it is worth this extra code. If we have time later, we can try racing workflows to see if `uvloop` actually provides a real benefit.

**Comment by BlakeASmith** [comment]
> Can you submit a PR that just does away with `uvloop`? I am not sure it is worth this extra code. If we have time later, we can try racing workflows to see if `uvloop` actually provides a real benefit.

Sure we can do that. I'll keep this branch in case we decide to integrate uvloop again later.
