### ISSUE TITLE
Develop fixture functions for database and file access

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#58]
**Depends on #52**

Develop a set of database access functions to replace all database access that occurs in existing workflows. Abstracting the database calls out of the workflow code will allow the backing implementation to be improved without requiring modifying the workflow code.

Develop an API for accessing files. Initially, it will be backed by direct filesystem access. This will be replaced by HTTP or other protocol in the near future.

**Comment by BlakeASmith** [comment]
Replaced by clubhouse story https://app.clubhouse.io/virtool/story/125/create-abstract-classes-for-database-functionality
