### ISSUE TITLE
Enhanced subtractions fixture

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-workflow#61]
# Background
These are FASTA format files that are used for eliminating host and background information from the analysis. Currently, only one subtraction per analysis is allowed. We want to support multiple subtractions or zero in the near future.

# Fixture
- named `subtractions`
- it is an iterable of subtraction objects
- each subtraction has a `path` attribute
- using the `subtractions` fixture triggers the download of the subtraction data to the analysis working tree
- the subtraction can currently be found at `job["args"]["subtraction_id"]` for analysis jobs; in the future this will be a list of IDs

**Comment by BlakeASmith** [comment]
@igboyes Where are the subtractions downloaded from?

**Comment by BlakeASmith** [comment]
> using the subtractions fixture triggers the download of the subtraction data to the analysis working tree
@igboyes Where are the subtractions downloaded from?

**Comment by BlakeASmith** [comment]
I'm thinking having a dataclass which has all of the fields from the `subtraction` document. 

```python
@dataclass
class Subtraction:
    name: str
    nickname: str
    path: Path 
    gc: Dict[str, float]
    count: int
```

**Comment by igboyes** [comment]
Data is in folder at `<data_path>/subtractions/<subtraction_id>` and contains a number of files:
- subtraction.fa.gz
- reference.1.bt2 
- reference.3.bt2
- reference.2.bt2
- reference.4.bt2
- reference.rev.1.bt2
- reference.rev.2.bt2

I think we should have three path attributes:
- `path`: folder path
- `fasta_path`: path to compressed FASTA file
- `bowtie2_index_path`: Bowtie requires a path to the index file prefix without any file extension

**Comment by igboyes** [comment]
Output of `tree` FYI:
```
subtractions/
└── g79r54x8
    ├── reference.1.bt2
    ├── reference.2.bt2
    ├── reference.3.bt2
    ├── reference.4.bt2
    ├── reference.rev.1.bt2
    ├── reference.rev.2.bt2
    └── subtraction.fa.gz
```

**Comment by BlakeASmith** [comment]
> Data is in folder at `<data_path>/subtractions/<subtraction_id>` and contains a number of files:
> 
> * subtraction.fa.gz
> * reference.1.bt2
> * reference.3.bt2
> * reference.2.bt2
> * reference.4.bt2
> * reference.rev.1.bt2
> * reference.rev.2.bt2
> 
> I think we should have three path attributes:
> 
> * `path`: folder path
> * `fasta_path`: path to compressed FASTA file
> * `bowtie2_index_path`: Bowtie requires a path to the index file prefix without any file extension

Ok so to clarify;

- `path` in this case would be <data_path>/subtractions/<subtraction_id>
- `fasta_path` would be `path/"subtraction.fa.gz"`

And I'm not quite understanding what `bowtie2_index_path` would be here. What exactly is the `index` in this context?

**Comment by BlakeASmith** [comment]
> Output of `tree` FYI:
> 
> ```
> subtractions/
> └── g79r54x8
>     ├── reference.1.bt2
>     ├── reference.2.bt2
>     ├── reference.3.bt2
>     ├── reference.4.bt2
>     ├── reference.rev.1.bt2
>     ├── reference.rev.2.bt2
>     └── subtraction.fa.gz
> ```

I can go ahead and write the fixture assuming that these files are present, but what is the plan for loading these files into the workflow container? 

I'm assuming we will need to download them from somewhere either before the workflow runs, or when the `subtractions` fixture is instantiated. 

I might be missing something here.
