### ISSUE TITLE
Create A Separate Database API Process and Client Library

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#83]
Issue #44 discusses the issues involved with avoiding direct database access within workflows.

Issue #52 documents the various database calls which are made from the current workflow/job implementations in [virtool/virtool/jobs](https://github.com/virtool/virtool/tree/master/virtool/jobs)

Ultimately, the only way to completely and safely manage database access within workflows is to perform the database calls in a separate process (on a separate machine), and provide an HTTP API (or similar). The server will access the database on behalf of the workflows and ensure that workflows are only able to modify those database documents which relate directly to their `job_id`.

## Per-job Permissions via Tokens

One method to limit access on a per-job basis, and ensure that the process making the request is actually the process which is executing that job, is to provide a unique, and difficult to guess, *token* to the workflow process in place of the database ID for the job. The server itself would maintain a mapping between the tokens and job IDs.

When the workflow developer makes a request to the server, via the client library, this token will be provided and the server will selectivley provide information / make updates based on the information provided in the job's database document.

**Comment by igboyes** [comment]
In progress. Tracked in Clubhouse.
