### ISSUE TITLE
Improve Testing Environment

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#84]
Currently there is no simple way to test individual workflow functions which rely on many different fixtures. Additionally the MongoDB database must be running and initialised with the correct values in order for many fixtures to work. This greatly complicates unit testing and we can certainly do better.

**Please comment on this issue with any ideas on how testing can be simplified and/or which areas are currently hard to test.**

**Comment by BlakeASmith** [comment]
## Auto-loading of Fixtures

Currently fixtures are only automatically imported when running the entire workflow using the CLI. A simple way to import all the same fixtures which would be available when using the CLI is needed. 

The tester should be able to write code something like this;

```python
from virtool_workflow_runtime.testing import runtime_scope

async def test_function_using_fixtures():
	await runtime_scope.bind(my_function)()
	...
	
```

**Comment by igboyes** [comment]
Is `my_function()` a fixture?

**Comment by BlakeASmith** [comment]
> Is `my_function()` a fixture?

`my_function` is a function that uses fixtures in it's parameters. Not a fixture itself

**Comment by igboyes** [comment]
Can the solution look like the following?:
```python
async def test_function_using_fixtures(runtime):
	runtime.bind(my_function)
```

**Comment by BlakeASmith** [comment]
> Can the solution look like the following?:
> 
> ```python
> async def test_function_using_fixtures(runtime):
> 	runtime.bind(my_function)
> ```

Yes that is doable.

**Comment by igboyes** [comment]
Please do it then.
