### ISSUE TITLE
Index `manifest` and `sequence_otu_map` Fixtures

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#92]
The index manifest and `sequence_otu_map`, in `virtool/virtool`, is fetched from the database in `virtool.jobs.analysis.get_index_info` and added to the `job.params` in `virtool.jobs.analysis.check_db`.

New fixtures should be created for `manifest` and `sequence_otu_map` under the `virtool_workflow.analysis` package.

**Comment by igboyes** [comment]
I am currently working on this. It makes more sense for this data to be in the `indexes` fixture (#86).

**Comment by BlakeASmith** [comment]
> I am currently working on this. It makes more sense for this data to be in the `indexes` fixture (#86).

Ok perfect. I agree.
