### ISSUE TITLE
Consider `history` Fixture

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/virtool-workflow#93]
`virtool_core.history.db.patch_to_version` uses OTU change documents from the database to revert an
OTU document (dict) to a previous version.

`patch_to_version` accesses the database, so it shouldn't be used directly within workflows.

I propose that we add a `history` fixture with a `patch_to_version` method.

```python
@step
def use_history(history):
	...
	await history.patch_to_version(...)
	...
```

**Comment by igboyes** [comment]
This should be hidden behind the `indexes` fixture. Closing... for now.
